//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Sprintthat.Domain.Entity;
using System.Data.Entity.ModelConfiguration;

namespace Sprintthat.Mapping
{
    public class ModuleMap : EntityTypeConfiguration<ModuleEntity>
    {
        public ModuleMap()
        {
            // table
            ToTable("Sys_Module", "dbo");

            // keys
            HasKey(t => t.FId);

            // Properties
            Property(t => t.FId)
                .HasColumnName("F_Id")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.FParentId)
                .HasColumnName("F_ParentId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FFullName)
                .HasColumnName("F_FullName")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FIcon)
                .HasColumnName("F_Icon")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FUrlAddress)
                .HasColumnName("F_UrlAddress")
                .HasMaxLength(500)
                .IsOptional();
            Property(t => t.FDescription)
                .HasColumnName("F_Description")
                .HasMaxLength(500)
                .IsOptional();
            Property(t => t.FCreatorTime)
                .HasColumnName("F_CreatorTime")
                .IsOptional();
            Property(t => t.FCreatorUserId)
                .HasColumnName("F_CreatorUserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FLastModifyTime)
                .HasColumnName("F_LastModifyTime")
                .IsOptional();
            Property(t => t.FLastModifyUserId)
                .HasColumnName("F_LastModifyUserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FDeleteTime)
                .HasColumnName("F_DeleteTime")
                .IsOptional();
            Property(t => t.FDeleteUserId)
                .HasColumnName("F_DeleteUserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FIsExpand)
                .HasColumnName("F_IsExpand")
                .IsOptional();
            Property(t => t.FIsLeaf)
                .HasColumnName("F_IsLeaf")
                .IsOptional();

            // Relationships
        }
    }
}

