//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Sprintthat.Domain.Entity;
using System.Data.Entity.ModelConfiguration;

namespace Sprintthat.Mapping
{
    public class UserLogonMap : EntityTypeConfiguration<UserLogonEntity>
    {
        public UserLogonMap()
        {
            // table
            ToTable("Sys_UserLogon", "dbo");

            // keys
            HasKey(t => t.FId);

            // Properties
            Property(t => t.FId)
                .HasColumnName("F_Id")
                .IsRequired();
            Property(t => t.FAccount)
                .HasColumnName("F_Account")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.FPassword)
                .HasColumnName("F_Password")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.FName)
                .HasColumnName("F_Name")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.FCreateTime)
                .HasColumnName("F_CreateTime")
                .IsRequired();
            Property(t => t.FRoleLevel)
                .HasColumnName("F_RoleLevel")
                .IsRequired();

            // Relationships
        }
    }
}

