//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Sprintthat.Domain.Entity
{
    public  class ModuleEntity
    {
        public ModuleEntity()
        {
        }

        public string FId { get; set; }
        public string FParentId { get; set; }
        public string FFullName { get; set; }
        public string FIcon { get; set; }
        public string FUrlAddress { get; set; }
        public string FDescription { get; set; }
        public System.DateTime? FCreatorTime { get; set; }
        public string FCreatorUserId { get; set; }
        public System.DateTime? FLastModifyTime { get; set; }
        public string FLastModifyUserId { get; set; }
        public System.DateTime? FDeleteTime { get; set; }
        public string FDeleteUserId { get; set; }
        public int? FIsExpand { get; set; }
        public int? FIsLeaf { get; set; }

    }
}