//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace Sprintthat.Domain.Entity
{
    public class UserLogonEntity
    {
        public UserLogonEntity()
        {
        }

        public System.Guid FId { get; set; }
        public string FAccount { get; set; }
        public string FPassword { get; set; }
        public string FName { get; set; }
        public System.DateTime FCreateTime { get; set; }
        public int FRoleLevel { get; set; }

    }
}